parameters: {}
environment: {}
packages:
    - name: auth
      shared: false
      environment:
        SUPABASE_URL: "${SUPABASE_URL}"
        SUPABASE_KEY: "${SUPABASE_KEY}"
        SUPABASE_SECRET_KEY: "${SUPABASE_SECRET_KEY}"
        UTILITY_ACCT: "${UTILITY_ACCT}"
        UTILITY_PASS: "${UTILITY_PASS}"
      parameters: {}
      annotations: {}
      functions:
        - name: supabase_main
          binary: false
          main: "main"
          runtime: python:default
          web: true
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
