parameters: {}
environment:
  SUPABASE_URL: "${SUPABASE_URL}"
  SUPABASE_KEY: "${SUPABASE_KEY}"
packages:
    - name: auth
      shared: false
      environment:
        SUPABASE_SECRET_KEY: "${SUPABASE_SECRET_KEY}"
        UTILITY_ACCT: "${UTILITY_ACCT}"
        UTILITY_PASS: "${UTILITY_PASS}"
      parameters: {}
      annotations: {}
      functions:
        - name: main
          runtime: python:default